include: package:very_good_analysis/analysis_options.3.1.0.yaml

analyzer:
  exclude: [build/**]
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true
    package_api_docs: true
    public_member_api_docs: true
    file_names: false
