include: package:very_good_analysis/analysis_options.3.1.0.yaml
analyzer:
  exclude:
    - build/**
linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true
    public_member_api_docs: true
    file_names: false
