name: xpns_trckr_api
description: The next free, open source, one billion dollars, expenses tracking app.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  dart_frog: ^0.2.0
  equatable: ^2.0.5
  json_annotation: ^4.7.0
  meta: ^1.8.0

dev_dependencies:
  build_runner: ^2.3.2
  json_serializable: ^6.5.4
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
