name: xpns_trckr_api
description: The next free, open source, one billion dollars, expenses tracking app.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  dart_frog: ^0.3.0
  expense:
    path: 'packages/model/expense'
  expense_repository:
    path: 'packages/repository/expense_repository'
  in_memory_expense_repository:
    path: 'packages/repository/in_memory_expense_repository'

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
