name: in_memory_expense_repository
description: An in-memory implementation of the [ExpenseRepository] interface.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  expense:
    path: '../../model/expense'
  expense_repository:
    path: '../expense_repository'

dev_dependencies:
  test: ^1.16.0
  very_good_analysis: ^3.1.0
